name: Compile
on:
  push:
    branches:
      - main
jobs:
  linux-runtime:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm git gcc sfml meson ruby ruby-rake ruby-erb vim pkgconfig
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Copy mruby config file
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist"
    - name: Compile Rubytron
      run: ninja -C build
    - name: Upload Linux Runtime Header
      uses: actions/upload-artifact@v4
      with:
        name: linux-runtime-header
        path: build/src/Editor/runtime-linux.h

  macos-runtime:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        brew install meson sfml openal-soft
    - name: Copy mruby config file
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Setup Rubytron
      run: |
        meson setup build --prefix="$PWD/dist"
    - name: Compile Rubytron
      run: ninja -C build
    - name: Upload macOS Runtime Header
      uses: actions/upload-artifact@v4
      with:
        name: macos-runtime-header
        path: build/src/Editor/runtime-darwin.h

  linux:
    needs: [
      linux-runtime,
      macos-runtime
    ]
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm git gcc sfml meson ruby ruby-rake ruby-erb vim pkgconfig
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Copy mruby config file
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist" -Dcpp_args=-DMULTI_EXPORT
    - uses: actions/download-artifact@v4
      with:
        name: macos-runtime-header
        path: build/src/Editor
    - name: Compile Rubytron
      run: meson install -C build
    - name: Upload Linux bundle
      uses: actions/upload-artifact@v4
      with:
        name: rubytron-linux
        path: dist/linux
        retention-days: 5

  macos:
    needs: [
      linux-runtime,
      macos-runtime
    ]
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        brew install meson sfml openal-soft
    - name: Copy mruby config file
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Setup Rubytron
      run: |
        meson setup build --prefix="$PWD/dist" -Dcpp_args=-DMULTI_EXPORT
    - uses: actions/download-artifact@v4
      with:
        name: linux-runtime-header
        path: build/src/Editor
    - name: Compile Rubytron
      run: meson install -C build
    - name: Create macOS DMG
      run: |
        hdiutil create /tmp/tmp.dmg -ov -volname "Rubytron" -fs HFS+ -srcfolder dist/Rubytron.app
        hdiutil convert /tmp/tmp.dmg -format UDZO -o Rubytron.dmg
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: rubytron-macos
        path: dist/Rubytron.app
        retention-days: 5