name: Compile
on:
  push:
    branches:
      - main
jobs:
  linux-runtime:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm git gcc sfml meson ruby ruby-rake ruby-erb vim pkgconfig
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Copy mruby config file
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist"
    - name: Compile Rubytron
      run: ninja -C build
    - name: Upload Linux Runtime Header
      uses: actions/upload-artifact@v4
      with:
        name: linux-runtime-header
        path: build/src/Editor/runtime-linux.h

  macos-runtime:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        brew install meson sfml
    - name: Copy mruby config file
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Create macOS icon
      run: iconutil -c icns data/rubytron.iconset -o data/rubytron.icns
    - name: Setup Rubytron
      run: |
        meson setup build --prefix="$PWD/dist"
    - name: Compile Rubytron
      run: ninja -C build
    - name: Upload macOS Runtime Header
      uses: actions/upload-artifact@v4
      with:
        name: macos-runtime-header
        path: build/src/Editor/runtime-darwin.h

  windows-runtime:
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: |
        pip install meson ninja
        choco install mingw git
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install sfml:x64-windows
    - name: Add MinGW to PATH
      run: |
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Copy mruby config file
      run: cp rubytron.rb mruby/build_config.rb
    - name: Compile mruby
      run: |
        cd mruby
        rake
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist"
    - name: Compile Rubytron
      run: ninja -C build
    - name: Upload Windows Runtime Header
      uses: actions/upload-artifact@v4
      with:
        name: windows-runtime-header
        path: build/src/Editor/runtime-windows.h

  linux:
    needs: [
      linux-runtime,
      macos-runtime
    ]
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm git gcc sfml meson ruby ruby-rake ruby-erb vim pkgconfig
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Copy mruby config file
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist" -Dcpp_args=-DMULTI_EXPORT
    - uses: actions/download-artifact@v4
      with:
        name: macos-runtime-header
        path: build/src/Editor
    - name: Compile Rubytron
      run: meson install -C build
    - name: Upload Linux bundle
      uses: actions/upload-artifact@v4
      with:
        name: rubytron-linux
        path: dist/linux
        retention-days: 5

  macos:
    needs: [
      linux-runtime,
      macos-runtime
    ]
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        brew install meson sfml dylibbundler
    - name: Copy mruby config file
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Create macOS icon
      run: iconutil -c icns data/rubytron.iconset -o data/rubytron.icns
    - name: Setup Rubytron
      run: |
        meson setup build --prefix="$PWD/dist" -Dcpp_args=-DMULTI_EXPORT
    - uses: actions/download-artifact@v4
      with:
        name: linux-runtime-header
        path: build/src/Editor
    - name: Compile Rubytron
      run: meson install -C build
    - name: Fix macOS app
      run: dylibbundler -od -b -x dist/Rubytron.app/Contents/MacOS/rubytron -d dist/Rubytron.app/Contents/libs
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: rubytron-macos
        path: dist
        retention-days: 5