name: Compile
on:
  push:
    branches:
      - main
jobs:
  linux-runtime:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm git gcc sfml meson ruby ruby-rake ruby-erb vim pkgconfig zip minizip-ng
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Cache mruby
      id: cache-linux-mruby
      uses: actions/cache@v4
      with:
        path: mruby
        key: ${{ runner.os }}-mruby-${{ hashFiles('rubytron.rb') }}
    - name: Copy mruby config file
      if: steps.cache-linux-mruby.outputs.cache-hit != 'true'
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      if: steps.cache-linux-mruby.outputs.cache-hit != 'true'
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist"
    - name: Compile Rubytron
      run: meson install -C build
    - name: Upload Linux Runtime Header
      uses: actions/upload-artifact@v4
      with:
        name: runtime-linux-header
        path: build/src/Editor/runtime-linux.h

  macos-runtime:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        brew install meson sfml minizip-ng dylibbundler
    - name: Cache mruby
      id: cache-macos-mruby
      uses: actions/cache@v4
      with:
        path: mruby
        key: ${{ runner.os }}-mruby-${{ hashFiles('rubytron.rb') }}
    - name: Copy mruby config file
      if: steps.cache-macos-mruby.outputs.cache-hit != 'true'
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      if: steps.cache-macos-mruby.outputs.cache-hit != 'true'
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Create macOS icons
      run: |
        iconutil -c icns data/Editor/icon.iconset -o data/Editor/icon.icns
        iconutil -c icns data/Runtime/icon.iconset -o data/Runtime/icon.icns
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist"
    - name: Compile Rubytron
      run: meson install -C build
    - name: Upload macOS Runtime Header
      uses: actions/upload-artifact@v4
      with:
        name: runtime-macos-header
        path: build/src/Editor/runtime-darwin.h

  windows-runtime:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        choco install mingw imagemagick -y
        pip install meson ninja
    - name: Add MinGW to PATH
      run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -Append -FilePath $env:GITHUB_PATH
    - name: Compile to see
      run: |
        windres data/Runtime/runtime.rc
        ls
        ls data/Runtime
    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: vcpkg
        key: ${{ runner.os }}-vcpkg-sfml-minizip-static
    - name: Install vcpkg and SFML
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        choco install git
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install sfml:x64-mingw-static minizip-ng:x64-mingw-static
    - name: Cache mruby
      id: cache-windows-mruby
      uses: actions/cache@v4
      with:
        path: mruby
        key: ${{ runner.os }}-mruby-${{ hashFiles('rubytron.rb') }}
    - name: Copy mruby config file
      if: steps.cache-windows-mruby.outputs.cache-hit != 'true'
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      if: steps.cache-windows-mruby.outputs.cache-hit != 'true'
      run: |
        cd mruby
        rake
    - name: Create Windows icons
      run: |
        magick data/Editor/icon.iconset/icon_256.png -define icon:auto-resize=256,128,64,48,32,16 data/Editor/icon.icon
        magick data/Runtime/icon.iconset/icon_256.png -define icon:auto-resize=256,128,64,48,32,16 data/Runtime/icon.icon
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist"
    - name: Compile Rubytron
      run: meson install -C build
    - name: Upload Windows Runtime Header
      uses: actions/upload-artifact@v4
      with:
        name: runtime-windows-header
        path: build/src/Editor/runtime-windows.h

  linux:
    needs: [
      linux-runtime,
      macos-runtime,
      windows-runtime
    ]
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm git gcc sfml meson ruby ruby-rake ruby-erb vim pkgconfig zip minizip-ng
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Cache mruby
      id: cache-linux-mruby
      uses: actions/cache@v4
      with:
        path: mruby
        key: ${{ runner.os }}-mruby-${{ hashFiles('rubytron.rb') }}
    - name: Copy mruby config file
      if: steps.cache-linux-mruby.outputs.cache-hit != 'true'
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      if: steps.cache-linux-mruby.outputs.cache-hit != 'true'
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist" -Dcpp_args=-DMULTI_EXPORT
    - uses: actions/download-artifact@v4
      with:
        name: runtime-macos-header
        path: build/src/Editor
    - uses: actions/download-artifact@v4
      with:
        name: runtime-windows-header
        path: build/src/Editor
    - name: Compile Rubytron
      run: meson install -C build
    - name: Upload Linux bundle
      uses: actions/upload-artifact@v4
      with:
        name: rubytron-linux
        path: dist/linux
        retention-days: 5

  macos:
    needs: [
      linux-runtime,
      macos-runtime,
      windows-runtime
    ]
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        brew install meson sfml minizip-ng dylibbundler
    - name: Cache mruby
      id: cache-macos-mruby
      uses: actions/cache@v4
      with:
        path: mruby
        key: ${{ runner.os }}-mruby-${{ hashFiles('rubytron.rb') }}
    - name: Copy mruby config file
      if: steps.cache-macos-mruby.outputs.cache-hit != 'true'
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      if: steps.cache-macos-mruby.outputs.cache-hit != 'true'
      run: |
        cd mruby
        MRUBY_CONFIG=rubytron rake
    - name: Create macOS icons
      run: |
        iconutil -c icns data/Editor/icon.iconset -o data/Editor/icon.icns
        iconutil -c icns data/Runtime/icon.iconset -o data/Runtime/icon.icns
    - name: Setup Rubytron
      run: meson setup build --prefix="$PWD/dist" -Dcpp_args=-DMULTI_EXPORT
    - uses: actions/download-artifact@v4
      with:
        name: runtime-linux-header
        path: build/src/Editor
    - uses: actions/download-artifact@v4
      with:
        name: runtime-windows-header
        path: build/src/Editor
    - name: Compile Rubytron
      run: meson install -C build
    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: rubytron-macos
        path: dist
        retention-days: 5

  windows:
    needs: [
      linux-runtime,
      macos-runtime,
      windows-runtime
    ]
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        choco install mingw imagemagick -y
        pip install meson ninja
    - name: Add MinGW to PATH
      run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -Append -FilePath $env:GITHUB_PATH
    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: vcpkg
        key: ${{ runner.os }}-vcpkg-sfml-minizip-static
    - name: Install vcpkg and SFML
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        choco install git
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install sfml:x64-mingw-static minizip-ng:x64-mingw-static
    - name: Cache mruby
      id: cache-windows-mruby
      uses: actions/cache@v4
      with:
        path: mruby
        key: ${{ runner.os }}-mruby-${{ hashFiles('rubytron.rb') }}
    - name: Copy mruby config file
      if: steps.cache-windows-mruby.outputs.cache-hit != 'true'
      run: cp rubytron.rb mruby/build_config/.
    - name: Compile mruby
      if: steps.cache-windows-mruby.outputs.cache-hit != 'true'
      run: |
        cd mruby
        rake
    - name: Create Windows icons
      run: |
        magick data/Editor/icon.iconset/icon_256.png -define icon:auto-resize=256,128,64,48,32,16 data/Editor/icon.ico
        magick data/Runtime/icon.iconset/icon_256.png -define icon:auto-resize=256,128,64,48,32,16 data/Runtime/icon.ico
    - name: Setup Rubytron
      shell: bash
      run: meson setup build --prefix="$PWD/dist" -Dcpp_args=-DMULTI_EXPORT
    - uses: actions/download-artifact@v4
      with:
        name: runtime-linux-header
        path: build/src/Editor
    - uses: actions/download-artifact@v4
      with:
        name: runtime-macos-header
        path: build/src/Editor
    - name: Compile Rubytron
      run: meson install -C build
    - name: Upload Windows bundle
      uses: actions/upload-artifact@v4
      with:
        name: rubytron-windows
        path: dist/windows
        retention-days: 5